#基础镜像
FROM jiangnanjava/miniserver:latest

COPY ../msc-ekserver/build/libs/msc-ekserver.war /usr/local/tomcat/webapps
COPY config/server.xml /usr/local/tomcat/conf
USER root
EXPOSE 8080
CMD ["catalina.sh", "run"]